### ISSUE TITLE
Move away from `is_*` pattern

### ISSUE THREAD

**Issue by itegulov** [near/near-abi-rs#13]
Opening for visibility as this is something I and @miraclx had a discussion about.

`is_*` patterns in ABI are a little awkward as a lot of them are mutually exclusive, and some assumptions are implicit (if not `is_view` and not `is_init`, then this is a call function). Instead of having this pattern, we could have a field that defines what kind of function that is and another field that holds all optional modifiers like this:

```
{
  "name": "foo",
  "kind": "view" | "call",
  "modifiers: ("init" | "private" | "payable")[]
}
```

IMO this improves human readability but complicates parsing a bit. We should make a decision whether we are switching to the new pattern while we are still in the early-ish stages as this is a significant breaking change.

Also, tangential, but `call` is a confusing descriptor for a function kind as you also call view functions. Sometimes we call them transact functions (e.g. `workspaces-rs` call them that), which might be a better name?

**Comment by ChaoticTempest** [comment]
I definitely prefer having no "is" prefix since the modifiers name describes the segment already. As for the naming of call/view, if we do decide to call it "transact", better for it to be an adjective such as "transactive", but we should rope in devrel to see what they think since this can be inconsistent with what we got going on the docs side of things

cc @thisisjoshford

**Comment by idea404** [comment]
I prefer using categories for call types too. Best to see this implemented as an Enum class that returns the string values imo. Then perhapds SDKs and such could also implement this enum class for validating returned data

**Comment by itegulov** [comment]
Answering @austinabell's question from Slack (moving discussion here):

> What is the plan for handling this breaking change?

We could write a migration tool all the way from 0.1.0 through 0.2.0 to 0.3.0 (the release that would contain this if we agree that it makes sense). Thankfully the migration logic is going to be very trivial and we need to write something for 0.1.0->0.2.0 anyway. This should probably be its own tool, but can also be a part of `cargo-near`.

> Are we making our tools backwards compatible?

I think it does not make sense for `cargo-near` to support ABI formats that were only being output in SDK pre-releases. Most other ABI-related libraries are still unreleased. Anything else you were thinking of?

> What are the implications on dev console? Would we plan to support both formats?

I was thinking we could just apply the migration tool from above to convert all their ABIs (that I assume are just stored in a database) to the most up-to-date format. We need to talk to them and check if that is a reasonable approach from their perspective though.

> What is the benefit of this change for developers? My intuition is more readable/concise, but wondering if there are any other motivators

Yeah I mean the reasoning is purely decorative, but Mira and I independently had internalized similar feelings about the awkwardness of the current schema format. It is heavily based on the internals of `#[near_bindgen]`

> Basically, what is the cost of not making this change?

Just being stuck with the current schema format for the foreseeable future and having to answer occasional questions like "why is there no `is_call` field in the ABI? how do I know if a function is callable?" or "I am writing a frontend generator from ABI and wondering if `view` functions can be private?".

Also, the proposed format is in no way final and is very discussable. We could, for example, do an even stronger typed variant like this one:
```
{
  "name": "foo",
  "annotations": {
    "kind": "view"
  } | {
    "kind": "call",
    "modifiers": ("init" | "private" | "payable")[]
  }
}
```

**Comment by austinabell** [comment]
> We could write a migration tool all the way from 0.1.0 through 0.2.0 to 0.3.0 (the release that would contain this if we agree that it makes sense)

The issue may be that an ABI is embedded in an existing contract; it might not be so simple for some to just simply migrate existing ABIs. Take the example of Pagoda console, if someone adds a contract with an embedded ABI of an older version, there wouldn't be a clean way for them to migrate it at runtime since they are using a purely JS stack.

I wonder if it's possible for our types used with ABI tooling to deserialize any version and not require manual migration? And basically, support a minimal version that is compatible? Seems there would have to be duplication in JS/Rust and possibly slightly less efficient deserialization, but might make it easier for devs not requiring exact matches of ABI <-> SDK <-> `cargo-near`? This intuitively seems like it would be the biggest ergonomics issue.

> I think it does not make sense for cargo-near to support ABI formats that were only being output in SDK pre-releases. Most other ABI-related libraries are still unreleased. Anything else you were thinking of?

I agree; I think it's fine if we bork previous versions as long as we communicate and try to advise console on how actual bugs can be avoided. I guess this is more planning for changes in the future.

> Just being stuck with the current schema format for the foreseeable future and having to answer occasional questions like "why is there no is_call field in the ABI? how do I know if a function is callable?" or "I am writing a frontend generator from ABI and wondering if view functions can be private?".

> Also, the proposed format is in no way final and is very discussable. We could, for example, do an even stronger typed variant like this one:

Perhaps this would be beneficial to have some product input from developers on. Intuitively I prefer the format proposed, but it's unclear if that is true or if it's worth the breakage to change.

cc @janewang @DavidM-D do we have a process set up for doing user interviews for something like this?

**Comment by itegulov** [comment]
> The issue may be that an ABI is embedded in an existing contract; it might not be so simple for some to just simply migrate existing ABIs. Take the example of Pagoda console, if someone adds a contract with an embedded ABI of an older version, there wouldn't be a clean way for them to migrate it at runtime since they are using a purely JS stack.

If there is an existing contract with embedded ABI, then it should not matter as Pagoda console (presumably) pulls the ABI only once and then stores it somewhere locally, right? This only matters for devs who would keep using 4.1.0 prereleases which will not be supported much longer. I feel like directing devs to update to 4.1.0 or later is a reasonable request, WDYT?

> I wonder if it's possible for our types used with ABI tooling to deserialize any version and not require manual migration? And basically, support a minimal version that is compatible? Seems there would have to be duplication in JS/Rust and possibly slightly less efficient deserialization, but might make it easier for devs not requiring exact matches of ABI <-> SDK <-> cargo-near? This intuitively seems like it would be the biggest ergonomics issue.

Hmm, I think this might be doable. I will experiment with this.

**Comment by austinabell** [comment]
> If there is an existing contract with embedded ABI, then it should not matter as Pagoda console (presumably) pulls the ABI only once and then stores it somewhere locally, right? This only matters for devs who would keep using 4.1.0 prereleases which will not be supported much longer. I feel like directing devs to update to 4.1.0 or later is a reasonable request, WDYT?

This is not how it happens currently (there is no caching of the retrieval of the embedded ABI because a contract may upgrade their code and they would want the updated ABI), and this is still hit when Pagoda console hasn't indexed a contract with an outdated embedded ABI yet. I do think it's a reasonable request to push people to use 4.1 and above, but it just needs to be communicated and have the side effects minimized. @charleslavon looping you in now. Maybe you have some thoughts or suggestions on how we can handle this type of breaking change cross-team?

**Comment by itegulov** [comment]
Here is a PoC for schema version agnostic deserialization: https://github.com/near/near-abi-rs/pull/18

@austinabell not sure if that is what you had in mind, but feel free to start the conversation under that PR
